package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFC0C1FF)
val md_theme_dark_onPrimary = Color(0xFF1000A9)
val md_theme_dark_primaryContainer = Color(0xFF8083FF)
val md_theme_dark_onPrimaryContainer = Color(0xFF0D0096)
val md_theme_dark_secondary = Color(0xFFB9C7E0)
val md_theme_dark_onSecondary = Color(0xFF233144)
val md_theme_dark_secondaryContainer = Color(0xFF3C4A5E)
val md_theme_dark_onSecondaryContainer = Color(0xFFABB9D2)
val md_theme_dark_tertiary = Color(0xFF89CEFF)
val md_theme_dark_onTertiary = Color(0xFF00344D)
val md_theme_dark_tertiaryContainer = Color(0xFF009ADA)
val md_theme_dark_onTertiaryContainer = Color(0xFF002D43)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B1326)
val md_theme_dark_onBackground = Color(0xFFDAE2FD)
val md_theme_dark_surface = Color(0xFF0B1326)
val md_theme_dark_onSurface = Color(0xFFDAE2FD)
val md_theme_dark_surfaceVariant = Color(0xFF2D3449)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C4D7)
val md_theme_dark_outline = Color(0xFF908FA0)
val md_theme_dark_inverseOnSurface = Color(0xFF283044)
val md_theme_dark_inverseSurface = Color(0xFFDAE2FD)
val md_theme_dark_inversePrimary = Color(0xFF494BD6)
val md_theme_dark_surfaceTint = Color(0xFFC0C1FF)
val md_theme_dark_outlineVariant = Color(0xFF464554)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surfaceContainer = Color(0xFF171F33)
val md_theme_dark_surfaceContainerHigh = Color(0xFF222A3D)

